### ISSUE TITLE
feat: There should be functions to retrieve districts from an specific division, upazillas from an specific district etc.. 

### ISSUE THREAD

**Issue by saifscripts** [Azim-Ahmed/bd-divisons-to-unions#1]
Example:

// To get all districts from Dhaka division
const districtsFromDhaka = getDistricts('30');

**Comment by saifscripts** [comment]
I have implemented these functions in my project. I can contribute if you want.

**Comment by Azim-Ahmed** [comment]
Thank you for your contribution.

**Comment by saifscripts** [comment]
Thank you for accepting my PR <3
